php-Task7/mshop/routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (){
    return 'INDEX';
});


Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => 'auth'
], function(){
    //Auth::logout();
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/products', 'ProductController');
    Route::resource('/orders', 'OrderController');  //orders does not work
    Route::resource('/payementmethods', 'PayementMethodController');
});




Auth::routes();

php-Task7/mshop/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'price',
        'quantity',
        'description',
        'image',
        'category_id',
        'user_id'
    ];
}

php-Task7/mshop/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('admin.product.index',['products' => Product::all()]);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.create',[
            'products'=> Product::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        

        $product = Product::create($request->all());
        return redirect(route('admin.products.show', $product));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.product.show', [
            'product'=> $product
        ]); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin.product.edit',[
            'product' => $product,
            'products' => Product::all()
        ]);

       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->update($request->all());
        return redirect(route('admin.products.show', $product));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return  redirect(route('admin.products.index'));
    }
}

php-Task7/mshop/resources/views/admin/product/create.blade.php
@extends('layouts.app')

@section('title', 'All Products')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Products</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item"><a href="{{route('admin.products.index')}}">Products </a></li>
              <li class="breadcrumb-item active">Create New Product</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card card-body">
              <form action="{{route('admin.products.store')}}", method="post">
                  @include('admin.product.form')
              </form>
                 
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

php-Task7/mshop/resources/views/admin/product/edit.blade.php
@extends('layouts.app')

@section('title', 'All Categories')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Categories</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item"><a href="{{route('admin.products.index')}}">Categories </a></li>
              <li class="breadcrumb-item active">Create New Category</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card card-body">
              <form action="{{route('admin.products.update', $product)}}", method="post">
                  @method('PUT')
                  @include('admin.product.form')
              </form>
                 
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

php-Task7/mshop/resources/views/admin/product/form.blade.php
@csrf
<div class="form-group">
<label for="name">Name</label>
<input type="text" name="name" id="name" class="form-control" value="{{ isset($product)?$product->name : '' }}">
        @if($errors->first('name'))
<br>
        <span class="alert alert-danger">
            {{ $errors->first('name')}}
        </span>
         @endif
    </div>

    <div class="form-group">
<label for="price">price</label>
<input type="text" name="price" id="price" class="form-control" value="{{ isset($product)?$product->price : '' }}">
        @if($errors->first('price'))
<br>
        <span class="alert alert-danger">
            {{ $errors->first('price')}}
        </span>
         @endif
    </div>  

    <div class="form-group">
<label for="quantity">quantity</label>
<input type="text" name="quantity" id="quantity" class="form-control" value="{{ isset($product)?$product->quantity : '' }}">
        @if($errors->first('quantity'))
<br>
        <span class="alert alert-danger">
            {{ $errors->first('quantity')}}
        </span>
         @endif
    </div>

    <div class="form-group">
<label for="image">image</label>
<input type="text" name="image" id="image" class="form-control" value="{{ isset($product)?$product->image : '' }}">
        @if($errors->first('image'))
<br>
        <span class="alert alert-danger">
            {{ $errors->first('image')}}
        </span>
         @endif
    </div>   

    <div class="form-group">
<label for="category_id">category_id</label>
<input type="text" name="category_id" id="category_id" class="form-control" value="{{ isset($product)?$product->category_id : '' }}">
        @if($errors->first('category_id'))
<br>
        <span class="alert alert-danger">
            {{ $errors->first('category_id')}}
        </span>
         @endif
    </div>


 <div class="form-group">
<label for="user_id">user_id</label>
<input type="text" name="user_id" id="user_id" class="form-control" value="{{ isset($product)?$product->user_id : '' }}">
        @if($errors->first('user_id'))
<br>
        <span class="alert alert-danger">
            {{ $errors->first('user_id')}}
        </span>
         @endif
    </div>         
     
<div class="form-group">
<label for="description">Description</label>
    <textarea name="description" id="description" cols="30" rows="10" class="form-control">
        {{ isset($product)?$product->description : '' }}
    </textarea>
@if($errors->first('description'))
<br>
<span class="alert alert-danger">
    {{ $errors->first('description')}}
</span>
@endif
</div>
<div class="text-center">
    <button type="submit" class="btn btn-success">Save</button>
</div>




                      

php-Task7/mshop/resources/views/admin/product/index.blade.php
@extends('layouts.app')

@section('title', 'All Products')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Products</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item active">All products</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card card-body">
              <div class="row">
                  <div class="col">
                        <form>
                        <select name="limit" id="">
                            <option value="5" {{ Request::get('limit') == 5? 'selected' : '' }}>5</option>
                            <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                            <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                        </select>
                        <button type="submit"> Update</button>
                    </form>
                  </div>
                  
                  <div class="col text-center">
                  <form action="">
                        <input type="text" name="search" class="form-control">
                        <button type="submit" class="btn btn-info">Searching</button>
                         <a href="{{route('admin.products.index')}}">Reset</a>   
                    </form>
                  </div>
                  <div class="col text-right">
                      <a href="{{route('admin.products.create')}}" class="btn btn-success">create</a>
                  </div>
              </div>
              
          <table class="table table-bordered">
              <thead>
                  <tr>
                      <th>#</th>
                      <th>name</th>
                      <th>price</th>
                      <th>quantity</th>
                      <th>description</th>
                      <th>image</th>
                      <th>cat_ID</th>
                      <th>user_ID</th>
                      <th>Actions</th>
                  </tr>
              </thead>
              <tbody>
                  @foreach($products as $product)
                  <tr>
                      <td>{{ $product->id }}</td>
                      <td>{{ $product->name }}</td>
                      <td>{{ $product->price }}</td>
                      <td>{{ $product->quantity }}</td>
                      <td>{{ $product->description }}</td>
                      <td>{{ $product->image }}</td>
                      <td>{{ $product->category_id }}</td>
                      <td>{{ $product->user_id }}</td>
                    
                      <td>
                         <a href="{{route('admin.products.show', $product)}}" class="btn btn-info">Show</a>
                         <a href="{{route('admin.products.edit', $product)}}" class="btn btn-primary">Edit</a>
                         <form action="{{ route('admin.products.destroy', $product) }}" method="post" class="d-inline-block">
                                      @csrf
                                      @method('DELETE')
                                      <button type="submit" class="btn btn-danger">Delete</button>
                          </form>
                      </td>
                  </tr>
                  @endforeach
              </tbody>
          </table>
         
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

php-Task7/mshop/resources/views/admin/product/show.blade.php
@extends('layouts.app')

@section('title', 'All Products')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Products</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item"><a href="{{route('admin.products.index')}}">Products </a></li>
              <li class="breadcrumb-item active">Show Product: {{$product->name}}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">

        <div class="row">
          <div class="card card-body">
              <h2>Title:<br> {{$product->name}}</h2>
              <p>Desciption: <br> {{$product->description}}</p>
              <p>Price: <br> {{ $product->price }}</p>
              <p>quantity: <br> {{ $product->quantity }} </p>
              <p>image: <br> {{ $product->image }}</p>
               <p>catgory: <br> {{ $product->category_id }}</p> 
               <p>user: <br> {{ $product->user_id }}</p>        
                 <a href="{{route('admin.products.edit', $product)}}" class="btn btn-primary">Edit</a>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection