phpTask-6/zcart/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('/groups', 'GroupsController');


Route::resource('/subgroups', 'SubgroupsController');
Route::resource('/categories', 'CategoriesController');

phpTask-6/zcart/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

phpTask-6/zcart/app/categories.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class categories extends Model
{
    protected $fillable = [
        'name',
        'description',
        'subgroup_id'   
    ];
}

phpTask-6/zcart/app/groups.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class groups extends Model
{
    protected $fillable = [
        'name',
        'description',   
    ];
}

phpTask-6/zcart/app/subgroups.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class subgroups extends Model
{
    protected $fillable = [
        'name',
        'description',
        'group_id'   
    ];
}

phpTask-6/zcart/app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\categories;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index' , ['categories' => categories::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( 'categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = categories::create($request->all());
        return redirect(route('categories.index', $category));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function show(categories $categories)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function edit(categories $category)
    {
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, categories $category)
    {
        $category->update($request->all());
        return redirect(route('categories.index', $category));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function destroy(categories $category)
    {
        $category->delete();
        return redirect(route('categories.index'));
    }
}

phpTask-6/zcart/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

phpTask-6/zcart/app/Http/Controllers/GroupsController.php
<?php

namespace App\Http\Controllers;

use App\groups;
use Illuminate\Http\Request;

class GroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('groups.index' , ['groups' => groups::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( 'groups.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $group = groups::create($request->all());
        return redirect(route('groups.index', $group));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\groups  $groups
     * @return \Illuminate\Http\Response
     */
    public function show(groups $groups)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\groups  $groups
     * @return \Illuminate\Http\Response
     */
    public function edit(groups $group)
    {
       return view('groups.edit', compact('group'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\groups  $groups
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, groups $group)
    {
        $group->update($request->all());
        return redirect(route('groups.index', $group));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\groups  $groups
     * @return \Illuminate\Http\Response
     */
    public function destroy(groups $group)
    {
        $group->delete();
        return redirect(route('groups.index'));
    }
}

phpTask-6/zcart/app/Http/Controllers/SubgroupsController.php
<?php

namespace App\Http\Controllers;

use App\subgroups;
use Illuminate\Http\Request;

class SubgroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('subgroups.index' , ['subgroups' => subgroups::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( 'subgroups.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $subgroup = subgroups::create($request->all());
        return redirect(route('subgroups.index', $subgroup));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\subgroups  $subgroups
     * @return \Illuminate\Http\Response
     */
    public function show(subgroups $subgroups)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\subgroups  $subgroups
     * @return \Illuminate\Http\Response
     */
    public function edit(subgroups $subgroup)
    {
        return view('subgroups.edit', compact('subgroup'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\subgroups  $subgroups
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, subgroups $subgroup)
    {
        $subgroup->update($request->all());
        return redirect(route('subgroups.index', $subgroup));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\subgroups  $subgroups
     * @return \Illuminate\Http\Response
     */
    public function destroy(subgroups $subgroup)
    {
        $subgroup->delete();
        return redirect(route('subgroups.index'));
    }
}

phpTask-6/zcart/resources/views/categories/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Create New Group</title>
  </head>
  <body>
    
    
    <div class="container">
        
        <form action="{{route('categories.store')}}" method="post">
                <div class="form-group">
                    @csrf   
                    <label >Add new subgroup</label>
                    <input type="text" class="form-control"  title="name" name ="name">
                    <textarea class="form-control"  name="description" id="" cols="30" rows="10"></textarea>
                    <input type="text" class="form-control"  title="subgroup_id" name ="subgroup_id">
                    <button class="btn btn-success" type = "submit">Add new category</button>
                    
                </div>
                
        </form>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

phpTask-6/zcart/resources/views/categories/edit.blade.php
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Edit Group</title>
  </head>
  <body>
    
    
    <div class="container">
        
        <form action="{{ route('categories.update', $category) }}" method="post">
            
                <div class="form-group">
                    @csrf   
                    @method('PUT')
                    <label >Edit category</label>
                    <input type="text" class="form-control" id="name" title="name" name ="name" value= "{{$category->name}}">
                    <textarea class="form-control" name="description" id="description" cols="30" rows="10">{{$category->description}}</textarea>
                    <input type="text" class="form-control"  title="subgroup_id" name ="subgroup_id" value= "{{$category->subgroup_id}}">
                    <button class="btn btn-success" type = "submit">Edit group</button>
                    
                </div>
                
        </form>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

phpTask-6/zcart/resources/views/categories/index.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Groups</title>
  </head>
  <body>
    
    
    <div class="container">
    <h1> Sub Groups</h1>
    <a class="btn btn-success mt-2" href="{{route('categories.create')}}">Create new category</a>
    <table class="table">
        <thead>
            <tr>
            <th scope="col">category_ID</th>
            <th scope="col">name</th>
            <th scope="col">desc.</th>
            
            <th scope="col">sub_category_ID</th>
            <th scope="col"></th>
            
            </tr>
        </thead>
        @foreach($categories as $categories)
        <tbody>
            <tr>   
                <th scope="row">{{$categories->id}}</th>
                <td>{{$categories->name}}</td>
                <td>{{$categories->description}}</td>
                <td>{{$categories->subgroup_id}}</td> 
                <td><a class="btn btn-info" href="{{route('categories.edit', $categories)}}">Edit</a> 
                <form action="{{ route('categories.destroy', $categories) }}" method="post" style="display: inline-block">
                 @csrf
                 @method('DELETE')
                 <button class="btn btn-danger">Delete</button>
                 </form>  </td> 
            
            </tr> 
        </tbody>
        @endforeach
    </table>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>